### ISSUE TITLE
Problema vista de modelo asociado a otro

### ISSUE THREAD

**Issue by fedetaladriz** [IIC2513-2019-2/syllabus#10]
Hola!

He estado con problemas al mostrar la vista de un modelo que está asociado 1:N con otro. Intenté varias cosas pero sigo con el mismo error. Digamos, que `X` belongsTo `Y` y, por el otro lado,  `Y` hasMany `X`. Para implementar esto, hice lo siguiente:

Al crear la migración, agregué la llave foránea en la tabla del modelo `X`, agregando lo siguiente:

~~~~
    YId: {
      type: Sequelize.INTEGER,
     references: {
        model: 'Y', 
        key: 'id', 
      }
    }
~~~~

Luego de correr la migración, agregué las relaciones en los modelos. En `X`:
~~~~
X.belongsTo(models.Y)
~~~~ 
y en Y: 
~~~~
Y.hasMany(models.X)
~~~~ 
Intenté también poniendole el parametro foreignKey a estas lineas.

Ahora mi problema: Agregué las rutas y vistas de ambos modelos. La vista index del modelo `Y` funciona perfectamente, pero al cargar el index de `X`, me tira el siguiente error:
~~~~
TypeError: Cannot read property 'name' of undefined 
~~~~
donde `name` es uno de los atributos de `Y`. Por esto, creo que al cargar el index de `X`, se está tratando de cargar la información del modelo `Y` (ya que `X` pertence a `Y`), pero, por algún motivo, no está encontrando el modelo `Y` asociado. 

Me faltó algún detalle? Le di muchas vueltas y creo que está todo bien. 
Gracias!

**Comment by gpvidal** [comment]
mmm.... Y tu solo en el modelo estás haciendo: `ctx.orm.model.findAll()`? Puedes hacer algo del estilo:

```js
const instances = await ctx.orm.model.findAll();
console.log(instances);
```

Y ver qué te está entregando?

Saludos,

**Comment by fedetaladriz** [comment]
Hola @gpvidal ! 
El problema estaba en la vista. Raramente, una linea de comentario que tenía entremedio se estaba ejecutando, no sé porqué. La asociación siempre estuvo bien hecha.

Muchas gracias por la ayuda! Saludos!
