### ISSUE TITLE
Problema con asociación mensajes-usuarios 

### ISSUE THREAD

**Issue by pablovejar** [IIC2513-2019-2/syllabus#12]
Hola! 
Estoy teniendo problemas con la asociación de la entidad mensajes y usuarios, esto es porque un mensaje tiene 2 id de usuario asociados y a su vez, un usuario tiene muchos mensajes.

Estoy implementando en el migrate código de la forma (para el up)
```
return queryInterface.addColumn(
      'nombre_del_modelo', //nombre del modelo a editar
      'clave', // clave que queremos agregar
      {
        type: Sequelize.INTEGER,
        references: {
          model: 'modelo',
          key: 'id',
        },
        onUpdate: 'CASCADE',
        onDelete: 'SET NULL',
      }
    );
```
Además, en los archivos de la carpeta models les estoy agregando la asociación de la forma:
```
models.nombre_del_modelo.belongsTo(models.usuario, {
      as: 'sentByUser',
      foreignKey: {
        name: 'sentBy',
        allowNull: false
      }
    });
    models.nombre_del_modelo.belongsTo(models.usuario, {
      as: 'receivedByUser',
      foreignKey: {
        name: 'receivedBy',
        allowNull: false
      }
    });
```
Pero esto me genera problemas al hacer la migración, porque me reconoce solo una llave extra, que sería la "clave" que defini en el archivo de migrate, entonces me deja la tabla con solo una referencia a otra tabla y no me toma en cuenta lo que defini en models. ¿Cuál es el problema de esto? Por favor ayuda :( :cry:

**Comment by gpvidal** [comment]
Puedes colocarle `async` al método `up` de la migración, y luego lo haces con dos `await`s. Si quieres otra solución, puede revisar qué es lo que hace `Promise.all([])` :wink: 

Saludos,
