### ISSUE TITLE
Duda de CRUD con Nested Routes

### ISSUE THREAD

**Issue by fperezm12** [IIC2513-2019-2/syllabus#14]
Hola, no hemos podido encontrar una forma de implementar la creación (y CRUD en general) de un modelo que debería hacerse desde la view de otro.
P. ej.  queremos crear un partido ingresando desde la view de cancha, por lo lo que seria algo del estilo:
`"canchas/id/partidos/new"`
Alguna sugerencia/orientación?
Gracias!

**Comment by gpvidal** [comment]
Hola @DaToMC9 ,

Cuando haces referencia a esa ruta, Estás entregando el parámetro también?
Dónde aparece ese error?

Saludos,

**Comment by DaToMC9** [comment]
Hola!
Por ahora el unico lugar en el que hago referencia a esa ruta es en la view de una cancha, usando newMatchPath (siguiendo el ejemplo de clases), el error se produce en toda la pagina, es decir no me deja hacer nada.

**Comment by gpvidal** [comment]
@DaToMC9 Puedes colocar ese trozo de código para verlo? Me imagino que haces un `ctx.url()` o algo similar, no?

**Comment by DaToMC9** [comment]
En el show de canchas:
...
'<div>
  <a href="<%= newMatchPath %>">Crear Partido</a>
</div>
...
'

En routes/matches.js

'
...
router.get('matches.list', '/', async (ctx) => {
  const matchesList = await ctx.orm.match.findAll();
  await ctx.render('matches/index', {
    matchesList,
    newMatchPath: ctx.router.url('matches.new'),
    editMatchPath: (match) => ctx.router.url('matches.edit', { id: match.id }),
    deleteMatchPath: (match) => ctx.router.url('matches.delete', { id: match.id }),
    viewMatchPath: (match) => ctx.router.url('matches.view', {id: match.id}),

  });
});
...
'

**Comment by gpvidal** [comment]
@DaToMC9 Ok, creo entender el problema.

En tu código colocaste `newMatchPath: ctx.router.url('matches.new')`, pero el router se pregunta ¿A qué cancha pertenece? porque tu ruta es `/canchas/:id/partidos` y no le estas pasando ese `:id`.

Saludos,

**Comment by DaToMC9** [comment]
Gracias por las respuestas, ahora no me queda claro donde exactamente tengo que pasarle el `:id`, 
¿En la misma definicion de `newMatchPath`?

**Comment by gpvidal** [comment]
Donde quieras utilizar (o hagas referencia a) esa ruta, que tiene ese parámetro.

Saludos,
