### ISSUE TITLE
Heroku y Postgres

### ISSUE THREAD

**Issue by benjamimo1** [IIC2513-2019-2/syllabus#15]
Hola! Una vez que hagamos deploy de la app en heroku esta no estará en el mismo entorno local que desde el cual corremos nuestra bdd Postgres por lo que necesitaremos una URL publica para poder conectarnos a esta. Es esto correcto? 
Me parece raro hacer deploy de la bdd de manera local y no en un servidor dedicado. O la bdd queda corriendo en heroku de manera local, alla?
Mi duda general es: Donde ha de correr la BDD para recibir las querys de la app en heroku.

**Comment by gpvidal** [comment]
Hola @akrebs2 ,

Recuerda que estamos usando `yarn` y no `npm`.
Probaste con esto? https://github.com/IIC2513-2017-2/syllabus/issues/11#issuecomment-330001589

Saludos,

**Comment by akrebs2** [comment]
Hola!

Lo pude resolver. Al final "daba lo mismo" (hasta donde entendí yo) correr las migraciones, porque al hacer el deploy en heroku se corren de todas formas. Así que ese paso que me causaba problemas se podía saltar.

Si alguien tiene dudas, yo lo que hice fue:

1. Bajarse el repo
2. Copiar la carpeta de la app en otro lugar (solo para no mezclar los git's de heroku con los del proyecto)
2. Meterse a esa carpeta desde el terminal

3.Correr:
`git init`
`heroku login` --> acá los va a llevar a un inicio de sesión en su navegador, ahí hay que meterse con las credenciales de la persona que creó la app en la página de heroku, acorde al tutorial de la issue referenciada)
`heroku git:remote -a nombre-de-la-app-creada-en-la-pagina-de-heroku`
`git add .`
`git commit -m “initial commit for heroku”`
`git push heroku master`

Quizás hayan un par de malas prácticas en estos pasos, pero si alguien está desesperado, funciona.

**Comment by gpvidal** [comment]
No es necesario copiar la carpeta en otro lado, ya que `heroku` se agrega como otro remote de `git` al que le puedes mandar tus cambios.

Con respecto a las migraciones es cierto, si te fijas en el archivo `package.json` del template, hay un script llamado `heroku-postbuild` que se ejecuta automáticamente subido tu código a `heroku`.

Esto está solucionado, así que lo cierro.

Saludos,
