### ISSUE TITLE
Relacion hasMany() sin crear nuevos atributos

### ISSUE THREAD

**Issue by nlvargas** [IIC2513-2019-2/syllabus#16]
Hola, 

Quiero crear una relación sport.hasMany(models.user) y user.hasMany(models.sport) para modelar que a un usuario le pueden gustar muchos deportes y un deporte puede ser "gustado" por muchos usuarios. 

El problema es que al agregar las relaciones, se crea un nuevo atributo sportId en el modelo de user, pero no es relevante para mí que sea un atributo del usuario (más si pueden ser muchos). ¿Cómo hago para crear la relación sin que se cree el atributo que los relaciones? ¿O más bien, cuál es la manera correcta de hacer esta relación?

**Comment by gpvidal** [comment]
No sé si la duda sigue, pero puedes ver algo de ese estilo aquí: https://github.com/IIC2513-2019-2/my-university/pull/6

Saludos,
