### ISSUE TITLE
Subir App a Heroku

### ISSUE THREAD

**Issue by Franco1605** [IIC2513-2019-2/syllabus#17]
Hola, estoy teniendo problemas para subir la app a heroku. Me imprime el siguiente error;
![Captura de pantalla de 2019-09-13 16-25-12](https://user-images.githubusercontent.com/42159289/64890481-264ac580-d646-11e9-9086-47ef3fc71eb4.png)
Seguí los pasos de la issue cerrada para este caso y los consejos de mi compañero que comentó ahí. Pero no lo he podido resolver.
Gracias de antemano.

**Comment by sormazabal** [comment]
Me sale el mismo error. Porfa si alguien lo ha solucionado que comparta algún tip :)

**Comment by NicolasLahsen** [comment]
Me aparece lo mismo

**Comment by NicolasLahsen** [comment]
Con mi compañero nos pasó eso. Lo que hicimos fue

1. Solucionar un error `internal server` en una de las rutas
2. Agregamos al archivo `.gitignore` `node_modules/`
3. Eliminamos el `package.json.lock` porque tenía conflictos con `yarn.lock`
4. Movimos el proyecto a una carpeta externa
5. Probamos el build denuevo.


Con eso nos funcionó, no se si alguno de estos pasos esta incorrecto, pero finalmente hicimos el deploy. Ojalá te sirva!

**Comment by sormazabal** [comment]
@NicolasLahsen , de casualidad te tiraba esto??: 

> ERROR: Cannot find "/tmp/build_3dfa9c550f1db4253f49148960161a6b/server/config/database.js". Have you run "sequelize init"?

**Comment by baaldana** [comment]
Hola, soy el compañero de @Franco1605 y seguimos con el mismo problema que @sormazabal, alguna novedad?

**Comment by sormazabal** [comment]
@baaldana Seguí este [tutorial](https://gawdiseattle.gitbook.io/wdi/00-config-deployment/deploy-node)  y me acaba de resultar. 
También creé un archivo ".sequelizerc" afuera del "src" y dentro lleva:

> var path = require('path')
> 
> module.exports = {
>   'config':          path.resolve( 'src','config', 'database.js'),
>   'migrations-path': path.resolve('src','migrations'),
>   'models-path':     path.resolve('src','models'),
>   'seeders-path':    path.resolve('src','seeders'),
> }

**Comment by gpvidal** [comment]
Hola a todos,

Ese es un problema debido a que están mezclando el uso de npm y de yarn.

Saludos,

**Comment by baaldana** [comment]
Ahora nos está mostrando un error de que no reconoce el environment de Node.js. Ya desinstalamos npm para probar y el error no cambió.
