### ISSUE TITLE
Problema Servidor

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2513-2019-2/syllabus#2]
Hola! 

Intento meterme al servidor, y me sale el siguiente error:

![image](https://user-images.githubusercontent.com/31079536/63235259-b859dc80-c206-11e9-8e42-68fae20cc17e.png)

Intento hacer lo que dice, pero siempre llego a lo mismo

**Comment by AmbrosioV** [comment]
Hola, somos dos, a mi me pasa lo mismo

**Comment by gpvidal** [comment]
Ya debería estar resuelto! :wink:
