### ISSUE TITLE
Uso de hidden types html

### ISSUE THREAD

**Issue by akrebs2** [IIC2513-2019-2/syllabus#21]
Hola!

No me queda muy clara la necesidad de tener que ocupar un form (y un hidden type) para hacer el botón de delete en el proyecto de ejemplo del curso (ejemplo a continuación)

```
<form action="<%- deleteItemPath(item) %>" method="POST">
         <input type="hidden" name="_method" value="delete" />
                <input type="submit" value="Delete" />
</form>
```
Sé que tiene que ver con que no queremos que se nos redirija a otra página, pero no entiendo cómo esto resuelve ese problema. Si alguien pudiese explicar los componentes de este código y la lógica se apreciaría harto.

Gracias!

**Comment by gpvidal** [comment]
Hola @akrebs2 ,

Esto es debido a que los únicos valores permitidos en la propiedad `method` del formulario son `GET` y `POST`. Pero, como hemos estudiado, existen más acciones HTTP como `PUT`, `PATCH`, `DELETE`, entre otros.

La forma de que un formulario envíe la información con esas otras acciones es a través de un _input_ oculto (_hidden_) de nombre `_method`. Este campo sobreescribe al campo `method` del formulario, permitiendo enviar la información mediante estas otras acciones.

Saludos,

**Comment by akrebs2** [comment]
Perfecto. Eso sí, me surge la duda de por qué es necesario pasar por un form para hacer estos requests. Por qué yo no podría ejecutar un request a través de un objeto tipo <a> en mi html.

Gracias por su tiempo.

**Comment by gpvidal** [comment]
Ahh porque los enlaces (tag `a`) siempre se resuelven mediante una acción `HTTP` `GET`. Aunque después, utilizando `JS` del lado del cliente, puedes habiar este comportamiento.
