### ISSUE TITLE
Duda CSS

### ISSUE THREAD

**Issue by akrebs2** [IIC2513-2019-2/syllabus#22]
Hola!

No entiendo muy bien a qué se refiere la "importancia" y el "origen (browser, user, author)" en el contexto de CSS. Aparece en los contenidos y lo preguntaron en una I1 pasada, pero no sé dónde se reflejan estas propiedades en un código css.

Gracias!

**Comment by gpvidal** [comment]
Hola @akrebs2 ,

Buena pregunta!

Tu puedes escribir css de la siguiente forma:

```css
p  {
  background-color: white;
}
```

Pero tu sabes que esa regla es muy genérica, por lo tanto, cualquier otra regla un poco más específica la "sobreescribirá". Sin embargo, si tu quieres que esa regla se respete a toda costa puedes colocar:

```css
p  {
  background-color: white !important;
}
```

Y esi hará que esa regla esté presente a toda cosa.

En cuanto a origen, por ejemplo, hay reglas que los navegadores colocan a disposición de los desarrolladores que son las que parten con `-o-`, `-webkit-`, `-moz-`, etc. Esas reglas son, por ejemplo, las que tienen relación con un origen.

Saludos,
