### ISSUE TITLE
Uso de <ul> en navbar - HTML

### ISSUE THREAD

**Issue by akrebs2** [IIC2513-2019-2/syllabus#23]
Hola!

Una pregunta, ¿es buena práctica ocupar listas en html? (haciendo la analogía de que no deberíamos ocupar tablas).

Estoy haciendo un navbar, y estoy analizando la posibilidad de que los elementos estén en una lista, como el siguiente ejemplo:

![Captura de Pantalla 2019-09-29 a la(s) 16 42 51](https://user-images.githubusercontent.com/37155646/65838368-cf491f80-e2d8-11e9-9c9f-d7e4426ed5ec.png)

Gracias!

**Comment by gpvidal** [comment]
Hola @akrebs2 ,

Una de las primeras preguntas que deberías hacerte con respecto a esto es si el elemento está siendo utilizado para lo que está hecho. Por ejemplo, en el caso de las tablas:

¿Está siendo bien utilizada la tabla? Y aquí tienes dos respuestas:

* Sí, porque está tabulando datos
* No, porque está posicionando elementos y no para mostrar una tabla con datos.

Si vas a ocupar una lista para hacer "una lista de enlaces", entonces funciona perfecto :wink: !

Saludos!
