### ISSUE TITLE
Funciones comunes

### ISSUE THREAD

**Issue by rmant** [IIC2513-2019-2/syllabus#25]
Hola,

Si tenguna una función que va a ser utilizada en varios routers distintos, como lo puedo hacer para no repetirla en cada uno? Estoy pensando en algo como un archivo de utils en el root.

En caso de poder hacerse esto, como puedo exportar estas funciones para que esten disponibles en el resto del codigo?

Gracias!

**Comment by gpvidal** [comment]
Hola @rmant ,

Creo que [esto](https://www.sitepoint.com/understanding-module-exports-exports-node-js/) podría servirte.

Saludos,
