### ISSUE TITLE
Duda redis y uuid4

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2513-2019-2/syllabus#27]
Podemos usar la libreria redis y uuid4 para crear un login mas seguro?

**Comment by gpvidal** [comment]
Hola @ljrodriguez1 ,

Para qué utilizarías Redis?

Saludos,

**Comment by ljrodriguez1** [comment]
Estoy ocupando redis como store de session, uuid4 no lo estoy ocupando

**Comment by gpvidal** [comment]
Y por qué no tu base de datos? Estás ocupando otro paquete?

Saludos,

**Comment by ljrodriguez1** [comment]
Estoy ocupando redis porque dijeron que era más seguro que usar de store mi
base de datos.

El único paquete que tuve que instalar fue async-redis y luego en app al
usar sección sobreescribo las funciones get set y delete de sessions.

Entiendo que esto lo que hace es que cada vez que quiero acceder a la data
de redis necesito una key, por lo tanto luego cuando creo la sesión puedo
realizar ctx.session.userId = id ya que el get de este atributo está
protegido por una key.

No estoy seguro si es una manera correcta/segura de hacerlo. No he podido
pillar mucha info en internet sobre manejo de sesiones y la mejor manera de
realizarlo.

**Comment by gpvidal** [comment]
Hola @ljrodriguez1 ,

Me quedan muchas dudas con respecto a que Redis es más seguro que tu base de datos.

Creo además que tienes una pequeña confusión con respecto al tema de la autenticación de usuarios.

El proceso es más o menos de esta forma:

1. El usuario ingresa sus credenciales (email y contraseña en my-university)
2. Se busca a un usuario que tenga ese email
3. Se revisa que su password (que fue guardada usando `bcrypt`) sea correcta.
4. Si es correcta, en el caso de `my-university`, se guarda el `id` de usuario en la  _cookie_ (`ctx.session.userId = user.id`)

Yo adicionalmente les pedí, y se los dije en clases, que no pueden guardar el `id` de usuario en la _cookie_, que debían hacer el login de otra forma. Por ejemplo, generando una cadena de caracteres larga y enviando eso como _cookie_. (Ver diapositiva 9 de clase de sesión).

Si bien, y para que lo sepan, nuestro _template_ encripta las _cookies_ (es decir, no se envía finalmente el `id`  en plano), se debe cumplir con la regla antes mencionada.

Saludos,

**Comment by gpvidal** [comment]
@ljrodriguez1 ,

y qué es lo que le mandas al usuario en la _cookie_?

**Comment by ljrodriguez1** [comment]
lo que le mando al usuario en la cockie es lo que le paso a ctx.session?

le sigo pasando el userId pero suponiendo que el store de Redis al hacer set y get usa una key.

Quizas es mejor que te lo mueste en persona porque creo que entendi mal para que servia redis en el manejo de sesiones

**Comment by gpvidal** [comment]
Mejor :+1:
