### ISSUE TITLE
Duda casos de uso

### ISSUE THREAD

**Issue by sjkinast** [IIC2513-2019-2/syllabus#3]
Los casos de uso deben solamente incluir el happy path? , es necesario hacer el diagrama con los casos de uso y los actores o solo mencionarlos?

**Comment by Banfanci** [comment]
Colgandome a lo antes mencionado, que se espera en el happy-path, debemos mencionar solo las acciones del usuario o tambien es necesario que pongamos como las acciones del sistema en respuesta a las del usuario??

**Comment by gpvidal** [comment]
Hola @Banfanci !

Debería ser el flujo completo :+1: 

Saludos,
