### ISSUE TITLE
Problemas de routing: viewListingPath is not defined

### ISSUE THREAD

**Issue by benjamimo1** [IIC2513-2019-2/syllabus#30]
Hola!
Quiero implementar que los elementos de mi crud sean clickeables y direccionen a un view individual por elemento. He:

Agregado un html.ejs asociado
En routes/elementos agregue un router.get especial para este html mencioando
A la hora de en el CRUD hacer el titulo del elemento clickeable 

`<td > <a href="<%- viewListingPath(listing) %>"> <%- listing.title %> </a> </td>`

Se genera el error de not defined, aun cuando si lo esta. Mas raro aun acciones del tipo 

`<td><a href="<%- editListingPath(listing) %>">Edit</a></td>`

No genera problemas, aun cuando son equivalentes.

Gracias

**Comment by gpvidal** [comment]
Hola @benjamimo1 ,

Puedes indicar el error?

Saludos,
