### ISSUE TITLE
Error: Missing credentials for "PLAIN"

### ISSUE THREAD

**Issue by isavega** [IIC2513-2019-2/syllabus#31]
Hola,

Estoy creando la alerta el mail. Segui los pasos de My University y consigure las variables del entorno de esta forma, segun la cuenta que me cree en SandGrid. 

Error: Missing credentials for "PLAIN"

La congifuracion del mail la tengo tal cual el template del curso, pero me sale que me faltan credenciales para PLAIN. Busque en google las posibles causas pero no logro dar con la solucion. Muchas gracias!

**Comment by gpvidal** [comment]
Hola @isavega ,

Ojo con las credenciales que usas, **no son las de tu cuenta**. Debes entrar en SendGrid y crear una API KEY. Revisa la sección de ayuda :wink: 

Saludos,

**Comment by isavega** [comment]
Efectivamente tengo mi api key, 

6VzVzRmsR9iLP9Xzpj1xQw

En el archivo .env modifique usuario por el nombre de la api (tambien probe con el id) y la pass con la api key. Es correcto? Porque aun me tira el mismo error :cry:

**Comment by isavega** [comment]
Efectivamente tengo mi api key,

![image](https://user-images.githubusercontent.com/42187168/66221290-15213180-e6a5-11e9-9f3c-81a6e2869c50.png)

En el archivo .env modifique usuario por el nombre de la api (tambien probe con el id) y la pass con la api key. Es correcto? Porque aun me tira el mismo error :cry: 

![image](https://user-images.githubusercontent.com/42187168/66221319-21a58a00-e6a5-11e9-82e2-eb60cad2b48b.png)

**Comment by gpvidal** [comment]
Revisaste [aqui](https://sendgrid.com/docs/API_Reference/SMTP_API/integrating_with_the_smtp_api.html)? Aquí aparece el nombre de usuario que deberías tener.

Saludos!

PD: Genera ua nueva API Key, a mi me llegó la tuya por mail :stuck_out_tongue:

**Comment by isavega** [comment]
Probe seteando el usuario, con/sin puerto/host y aun el mismo error 

![image](https://user-images.githubusercontent.com/42187168/66231179-38a3a680-e6bc-11e9-88fb-ec363a7e3be4.png)

![image](https://user-images.githubusercontent.com/42187168/66231402-d8f9cb00-e6bc-11e9-8c45-5e92f1b991de.png)

![image](https://user-images.githubusercontent.com/42187168/66231432-e616ba00-e6bc-11e9-8773-0fa91d1e07cc.png)

**Comment by gpvidal** [comment]
Hola @isavega ,

Tienes un problema en tu archivo `.envrc`, te recomiendo leer este [artículo](https://ajanthan.github.io/post/managing-environment-variables/)

Saludos,

**Comment by isavega** [comment]
Muchas gracias!!

**Comment by jotramon** [comment]
Hola, nosotros nos salio el mismo error! pero viendo esta issue no logro que se solucione. Que hay que arreglar?
saludos

**Comment by isavega** [comment]
Hola, 

Entre cambiar tantas veces las credenciales, me pifié y le borré el export que va antes de la variable que quieres exportar (archivo de variables de entorno). Le agregué eso y funcionó 😄

**Comment by jotramon** [comment]
genial, no me arroja error, pero no funciona :(

**Comment by jotramon** [comment]
funciono! no se como pero lo hizo :)
