### ISSUE TITLE
Uso de crypto

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2513-2019-2/syllabus#32]
Hola,

¿Podemos usar `crypto` para generar el _token_ de la _cookie_?

Ariel

**Comment by gpvidal** [comment]
Hola @ariel-m-s ,

**No te lo recomendaría**, si revisas la [página del paquete](https://www.npmjs.com/package/crypto) aparece un gran mensaje de que está obsoleto. Sin embargo, "It's now a built-in Node module" :smile: 

Saludos,
