### ISSUE TITLE
CSS no se ve en Heroku

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2513-2019-2/syllabus#33]
Hola, ¿por qué podría ser que en Heroku no se vea el CSS, siendo que en local sí?

Saludos!

**Comment by auirarrazaval** [comment]
Nos pasa exactamente lo mismo, el build dice algo relacionado con unas flag (?)
``` warning Ignored scripts due to flag ```
No tengo idea si será eso o no

**Comment by VicenteVicente** [comment]
Lo solucionamos agregando el `<link></link>` del `.css` 😄 en el `<head></head>` de `layout.html.ejs`
