### ISSUE TITLE
Rutas para JQuery

### ISSUE THREAD

**Issue by mora4** [IIC2513-2019-2/syllabus#34]
Hola,

No he logrado hacer funcionar alguno de los ejemplos de jquery vistos en clases. Obtengo el siguiente error en la consola del navegador: 

> GET http://localhost:3000/ejemplo.js net::ERR_ABORTED 404 (Not Found)

Donde debo ubicar el archivo js? y como debo hacer la ruta del src en el tag de script?

Gracias!

**Comment by gpvidal** [comment]
Hola @mora4 !

Subiré un ejemplo pronto!

Saludos,

**Comment by gpvidal** [comment]
@mora4 !

Aquí lo subí! https://github.com/IIC2513-2019-2/my-university/pull/9

**Comment by mora4** [comment]
Muchas gracias!
