### ISSUE TITLE
Manejo centralizado de errores

### ISSUE THREAD

**Issue by akrebs2** [IIC2513-2019-2/syllabus#35]
Hola!

Estoy intentando hacer un manejo centralizado de errores (404, 500, etc.), siguiendo la documentación de koa ([https://github.com/koajs/koa/wiki/Error-Handling](url)), sin embargo, no sé en qué archivo debería ir lo siguiente:
`app.on('error', (err, ctx) => {
});`

Feliz de recibir un par más de luces al respecto.

Gracias!

**Comment by gpvidal** [comment]
Hola @akrebs2 ,

La aplicación de `koa` sea crea en `src/app.js`. Ojo con este archivo, aquí se cargan los _middlewares_ necesarios para que el _template_ funcione.

Saludos,

**Comment by gpvidal** [comment]
Pero sigue el error?

**Comment by akrebs2** [comment]
Sip, sigue.

No logro que me redirija a "items/index" porque dice que hay una variable del ctx.state (una que nosotros definimos) que está undefined.

![Captura de Pantalla 2019-10-18 a la(s) 14 19 27](https://user-images.githubusercontent.com/37155646/67114473-54c24000-f1b2-11e9-8f7e-8488fae9a0db.png)

Eso está en el archivo app.js. Sé que entra al `if (ctx.status === 404)`, pero se cae al renderear, como dije.

**Comment by akrebs2** [comment]
Creo que ya sé cuál es el problema (pero no la solución). Al hacer render, el middleware nunca "pasó" por el archivo de rutas, en particular, no corrió la parte en donde se definen las variables de ctx.state, por ende, como el navbar (el cual tiene todas las páginas) pregunta por variables del ctx.state, se cae.

Ahora, una opción sería que el html que se abre no contenga el navbar (para que así no se tenga que preguntar por estas variables), pero como este (el navbar) esté definido en layout.html.ejs, no sé cómo tener un html que no "herede" de este layout. Quizás me podría dar algunas luces de cómo hacer esto :)

**Comment by gpvidal** [comment]
@akrebs2 puedes colocar ese `app.use(...)` justo antes de `app.use(routes.routes());`?

**Comment by akrebs2** [comment]
Lo acabo de hacer y no funciona :(

**Comment by gpvidal** [comment]
Hola @akrebs2 ,

Efectivamente lo que planteas en https://github.com/IIC2513-2019-2/syllabus/issues/35#issuecomment-543851164, es cierto. Es exactamente lo que está pasando. Está correcto que el _middleware_ que colocaste esté al principio.

Tal como mencionamos, nosotros ocupamos un _middleware_ (porque todo es _middleware_ en `koa`) para el *render*. Si te fijas [aquí](https://github.com/koajs/ejs#layouts) creo que te podría dar una idea para tu problema :wink:

Saludos,

**Comment by akrebs2** [comment]
Lo logré!

Era simplemente darle opciones al render. En particular, ocupé:
` await ctx.render('../errors/404',{
        layout: false,
      })`

Gracias profe!

**Comment by gpvidal** [comment]
Súper!
