### ISSUE TITLE
Guardar una nueva instancia de relación N a N

### ISSUE THREAD

**Issue by akrebs2** [IIC2513-2019-2/syllabus#38]
Hola!

Para nuestro proyecto estamos teniendo muchos problemas con guardar nuevas instancias de una relación N a N (un item tiene muchos tags y un tags pertenece a mucho items). En particular, al crear un item, al usuario se le pide una lista de tags (separados) por coma, y luego en la ruta debemos crear esta nueva instancia de la tabla intermedia, pero la realidad es que no nos está funcionando.

Leyendo la documentación de Sequelize, sabemos que en estos casos se agrega el método item.addTag(newTag), pero la verdad es que no nos ha funcionado (realmente hemos probado todas las variaciones, y leído muchos ejemplos de StackOverflow).

Sería ideal si en MyUniversity pudiesen subir un ejemplo de este tipo de relaciones, porque la verdad no lo hemos podido lograr.

**Comment by gpvidal** [comment]
Hola @akrebs2 !

Mira aquí! https://github.com/IIC2513-2019-2/my-university/pull/6 Hay un ejemplo para agregar alumnos a cursos (un alumno puede estar en muchos cursos, en un curso pueden haber muchos alumnos). En particular mira la migración `enroll-students-to-courses.js`.

Saludos,

**Comment by akrebs2** [comment]
Perfecto, me funcionó. Muchas gracias!
