### ISSUE TITLE
Uso de frameworks CSS

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2513-2019-2/syllabus#39]
Hola,

¿Podríamos comenzar a ocupar algún framework de CSS 🖌 para las siguientes entregas? En caso de que no, ¿podríamos al menos usar uno para la entrega final?

Saludos,
Ariel

**Comment by gpvidal** [comment]
Hola @ariel-m-s ,

No pueden ocupar ningún framework CSS, en ninguna etapa del proyecto.

Saludos,

**Comment by ariel-m-s** [comment]
Pucha 😢. Gracias!
