### ISSUE TITLE
[Entrega 2] - CRUD con Koa router

### ISSUE THREAD

**Issue by VicenteVicente** [IIC2513-2019-2/syllabus#4]
Hola, podrían subir un ejemplo o tutorial más detallado para hacer los CRUDs, en particular para el POST, pues no hemos encontrado ninguno bueno en internet. Saludos y gracias!

**Comment by gpvidal** [comment]
Hola @VicenteVicente ,

El ejemplo que vimos en clases lo puedes ver aquí:
https://github.com/IIC2513-2019-2/my-university/pull/1

Saludos,

**Comment by VicenteVicente** [comment]
Gracias!
