### ISSUE TITLE
Crear Rest api

### ISSUE THREAD

**Issue by ljrodriguez1** [IIC2513-2019-2/syllabus#40]
De acuerdo al enunciado 5 debemos empezar a implementar react en nuestra app, para esto yo creo crear una rest api para poder llamarla com Ajax dentro de react, para esto tengo tres dudas,

1- existe un templete para crear la api y que este en el estilo de nuestro template

2- es necesario implementar todos los métodos crear patch y delete, si no los necesito ocupar todos 

3- es conveniente crear una carpeta api donde estén estas o es mejor agregarlas en el router del modelo?

Saludos

**Comment by gpvidal** [comment]
Hola @ljrodriguez1 ,

Respondo tus dudas:

> 1- existe un templete para crear la api y que este en el estilo de nuestro template

Para poder, por ejemplo, retornar JSON desde el template puedes hacerlo agregando un objeto a `ctx.body`, del estilo `ctx.body = { prop: 'value' }`. Si quieres hacerla REST puedes utilizar un paquete como: https://github.com/SeyZ/jsonapi-serializer. Esto lo veremos mañana en clases.

> 2- es necesario implementar todos los métodos crear patch y delete, si no los necesito ocupar todos

No, no es necesario. Sin embargo, si lo preguntas con respecto al proyecto, debes consultar con tu ayudante.

> 3- es conveniente crear una carpeta api donde estén estas o es mejor agregarlas en el router del modelo?

Esta decisión depende más de ti. La opción que planteas es muy viable y fácil de implementar, pero también hemos visto que hay alumnos que incluso crean otra aplicación Koa solo para API. Va a depender de qué tan motivado estés.

Saludos,
