### ISSUE TITLE
Enviar datos desde servidor a componente React

### ISSUE THREAD

**Issue by gpvidal** [IIC2513-2019-2/syllabus#41]
Hola!

Voy a tratar de darles un par de guías para poder obtener información de la base de datos en sus componentes React:

### Usando datasets

Dentro de `HTML` existen unos atributos que comienzan con `data-` que permiten agregar información a un elemento. Estos son los famosos [*datasets*](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset).

Para ustedes hacer uso de esto, vamos a poner un ejemplo: Quiero, en una vista, mostrar un saludo al usuario con su nombre en un componente React. El usuario, se accede por medio de la variable `currentUser`.

Entonces, del lado del servidor, voy a hacer una vista que tenga lo siguiente:

*/src/views/users/_toolbar.html.ejs*
```html
<div id="user-toolbar" data-username="<%= currentUser.name %>"></div>
```

Luego, para que se muestre el componente React:

*/src/assets/js/app.jsx*
```js
// [...] aquí pueden haber otras cosas
const reactUserToolbar = document.getElementById('user-toolbar');

if (reactUserToolbar) {
  ReactDOM.render(<UserToolbar serverData={reactUserToolbar.dataset} />, reactUserToolbar);
}
// [...]
```

Y el componente, ahora del lado del cliente, podría verse así (se ha simplificado para hacerlo más fácil):

*/src/assets/js/components/UserToolbar.jsx*
```jsx
export default UserToolbar(props) {
  return <h1>Hola {props.serverData.username}!</h1>;
}
```

Como podrán darse cuenta, en este caso solo podrán pasar cadenas de texto. Por lo que si requieren pasar objetos o cosas más complejas podrían intentar con cosas como `JSON.stringify()` y `JSON.parse()`.

### Haciendo un request

Durante la clase que hizo @Polea012 , al final quedó un ejercicio propuesto que era que pudiesen leer información de una fuente externa. Este ejercicio (y su solución) puedes verlo [aquí](https://github.com/IIC2513-2019-2/syllabus/tree/master/clases/11%20React/react/examples/components).

Con esto ya tenemos la mitad del problema resuelto. Nos falta la parte en que disponibilizamos los datos.

Esto se puede lograr de forma bastante simple, agregando contenido a la propiedad `ctx.body`. Por ejemplo:

```js
router.get('courses.list', '/', async (ctx) => {
  const coursesList = await ctx.orm.course.findAll();
  ctx.body = coursesList;
}
```

Y lo anterior hará que el *output* del *request* sea un JSON. Luego, basta hacer extactamente lo mismo que en el ejercicio propuesto para poder cargar los datos en nuestro componente React.

Espero que esto les aclare algunas dudas, sino, siempre pueden seguir escribiendo aquí :smile: 

Saludos,

**Comment by akrebs2** [comment]
Profesor, una duda.

Si uno quiere enviar más de un solo elemento en un dataset, ¿cómo se hace? En particular, desearía enviar más de un dataset en esta línea de código:

`ReactDOM.render(<UserToolbar serverData={reactUserToolbar.dataset} />, reactUserToolbar);`

En mi caso necesito enviar un `TagsListContainer` y un `CategoriesListContainer`, los cuales vendrían siendo equivalentes a `reactUserToolbar`.

Gracias!

**Comment by akrebs2** [comment]
Ya lo logré jaja.

Por si a alguien le sirve:

En el html lo que hice fue darle muchos atributos tipo `data-` a un solo elemento html, y después ese era el encargado de pasar toda la info.

```
const backendInfo = document.getElementById('backend-info');`
if (backendInfo) {
  ReactDOM.render(<TagsList serverData={backendInfo.dataset}/>, backendInfo);
}
```
