### ISSUE TITLE
react-table y react-spring

### ISSUE THREAD

**Issue by cho19** [IIC2513-2019-2/syllabus#42]
Hola!

Queríamos preguntar si podemos utilizar estos paquetes:

- [react-table](https://github.com/tannerlinsley/react-table) para hacer unos filtros dinámicos en una tabla.
- [react-spring](https://www.react-spring.io/) para implementar animaciones

Gracias de antemano!

**Comment by gpvidal** [comment]
Hola @cho19 ,

Ok, solo por diversión :wink:  `react-spring` se ve bien avanzada :+1: 

Saludos,
