### ISSUE TITLE
Hacer Post desde React al Servidor

### ISSUE THREAD

**Issue by pita-horn** [IIC2513-2019-2/syllabus#43]
Hola!!
Trabajando en el proyecto me surgió el siguiente problema que no he logrado solucionar:
Necesito que mi componente react gatille un cambio en base de datos, un simple update. Para esto, creé una carpeta `routes/api` y dentro de ella el archivo js que gestiona el update con KoaRouter. Luego, en `src/app.js` agregué las líneas:
```
const api = require('./routes/api');
...
app.use(api.routes( ));
```
No obstante, al compilar no logra encontrar el módulo ./routes/api y lanza error. Luego en vez de eso intenté hacer el fetch con el path 'routes/api/' en lugar de sólo 'api/' y tampoco lograba encontrarlo (lanzaba error 404).

En internet recomendaban utilizar koa-mount pero tampoco funcionó.

¿Me falta alguna línea para que assets logre tener acceso a los archivos del servidor? ¿Hay alguna otra forma de gestionar un llamado al servidor desde el componente de react?
(Hice los tips de la issue #41 y me funcionó perfecto para que el componente reciba los datos, ahora me falta en el otro sentido jeje)

**Comment by gpvidal** [comment]
Hola @pita-horn !

Yo te recomendaría que trataras de mantener todas las rutas en el archivo del router "central" (`src/routes.js`).

Justo hice, en my-university, una implementación del estilo de la que quieres hacer, por lo que puedes consultarla directamente [aqui](https://github.com/IIC2513-2019-2/my-university/pull/10/files#diff-3ca5e313cdf02368ce63986a36207c94R8)

Avisame si no entiendes algo!

Saludos,

**Comment by pita-horn** [comment]
Muchas gracias!! El material de la PR solucionó mi problema con las rutas :)
Por si a alguien le sirve, logré hacer el fetch desde `assets/js/services` con:
```
return fetch(path, {headers: {} }).then(response => {
    return response.text()}
      ).then(json => {
    return json;
  });
```

**Comment by gpvidal** [comment]
Súper, gracias por la contribución! Incluso más sintético:

```js
return fetch(path)
  .then(response => reponse.json());
```
Así te queda listo para utilizar como objeto javascript :+1: 

Saludos,
