### ISSUE TITLE
Entrega proyecto 5

### ISSUE THREAD

**Issue by AmbrosioV** [IIC2513-2019-2/syllabus#44]
Hola, quería preguntar si podrían extender el plazo de la entrega. Se que es super de último minuto la petición, pero cualquier extensión nos ayudaría como grupo para poder desarrollar lo necesario 👍

**Comment by AmbrosioV** [comment]
Nose si hay más grupos en las mismas

**Comment by pedrobw** [comment]
Apoyo la moción, nos vendría bien a nosotros también

**Comment by baaldana** [comment]
ayuda

**Comment by gpvidal** [comment]
Voy a enviar un aviso al respecto.

Saludos,
