### ISSUE TITLE
Revisión/Recorrección de I1

### ISSUE THREAD

**Issue by BFFV** [IIC2513-2019-2/syllabus#45]
Hola!

Desde que entregaron las notas de la I1 no he podido revisar aún la prueba (fui la semana pasada al DCC pero no estaban las pruebas ahí),  ¿en qué momento se podrán revisar para así ver también la posibilidad de recorrección?

Gracias de antemano.

**Comment by gpvidal** [comment]
Hola  @BFFV ,

Primero que todo, la recorrección es un derecho del estudiante, por lo que yo no me puedo negar a que ustedes puedan recorregir su I1.

Sin embargo, con todo esto que ha pasado, mi prioridad ha estado en responder las dudas que me han llegado por las distintas vías y en preparar el plan que les compartí ayer.

¿Para cuando? La verdad es que es una pregunta complicada dada toda la incertidumbre actual, sin embargo, ten la certeza que sí tendrán la posibilidad de hacerlo.

Saludos,

**Comment by BFFV** [comment]
Gracias!
