### ISSUE TITLE
Input de un form en React

### ISSUE THREAD

**Issue by akrebs2** [IIC2513-2019-2/syllabus#46]
Hola!

Estoy teniendo problemas en recibir en el controlador la información de un componente react dentro de mi form.

El form en sí no está en react, sino que solo uno de sus inputs. Al imprimir el contenido de ctx.request.body, la información de este componente no aparece. Tengo entendido que uno debe implementar el método fetch cuando uno hace un form en react, sin embargo, en mi caso sólo tengo un input del form en react, no el form en sí, por ende, no sé cómo congeniar eso (¿se puede?).

Gracias de antemano.

**Comment by gpvidal** [comment]
Hola @akrebs2 ,

El render de tu componente es un input que está dentro de tu form?

Saludos,

**Comment by akrebs2** [comment]
Sí (o eso creo).

Mi código es algo así:
![Captura de Pantalla 2019-11-13 a la(s) 15 10 24](https://user-images.githubusercontent.com/37155646/68791291-c19cee80-0627-11ea-81c2-b6bd36d24da4.png)
La información de ese componente-react es la que no puedo acceder desde la ruta al enviar el form, mientras que la información de los otros inputs del form sí.

**Comment by gpvidal** [comment]
Ah ok! El tema ahí es que eso hace que como el componente hace render después que se carga el HTML, entonces el formulario no sabe que tiene que enviar ese input.

Yo te recomendaría que trataras de hacer el formulario completo con React, porque sería mala práctica que añadieras el input al formulario HTML que está fuera del componente. La idea es que estos sean autocontenidos.

Saludos,

**Comment by akrebs2** [comment]
Oka!

Gracias
