### ISSUE TITLE
Auth en api privada

### ISSUE THREAD

**Issue by mora4** [IIC2513-2019-2/syllabus#47]
Hola! 

Tengo un problema implementando una API privada, cuando cargo la pagina me sale "not found" y en la consola aparece el error:

>  Error: ENOENT: no such file or directory, open '/home/antonio/Desktop/U/web/grupo-hechoenguix/clothex/src/views/.html.ejs'

> 
Pero cuando hago que la API sea publica (poniendola sobre el _middleware_ en index) no tengo este problema.

Pienso que puedo tener un error al agregar el JWT al header Authorization, no entendi bien donde se debe hacer esto.

Tampoco me quedo claro cuando es que se llama la ruta api/auth, pasa automaticamente en el middleware o debo hacerlo en el login?

Muchas gracias!
Antonio Mora.

**Comment by gpvidal** [comment]
Hola @mora4 ,

Puedes ser que hayas creado un archivo mientras el servidor web corría y por eso no lo encuentra?

Saludos,
