### ISSUE TITLE
Credenciales PSQL

### ISSUE THREAD

**Issue by isavega** [IIC2513-2019-2/syllabus#5]
Hola, 

Tengo problemas para configurar mi usuario y contraseña de postgres, lo que me limita para realizar la migración. He usado los siguientes comandos (ubuntu):

sudo -i -u postgres
Guiandome con el siguiente tutorial: https://www.digitalocean.com/community/tutorials/como-instalar-y-utilizar-postgresql-en-ubuntu-16-04-es;

Pero al momento de crear un nuevo rol no me deja, me quedo con el usuario de postgres. Pensé en quedarme con el usuario predeterminado y crear la credenciales con usuario:postgres y password:''' pero me tira error. Tambien probé con las credenciales de mi companero y tampoco me deja. Qué puedo hacer? No puedo avanzar si no lo soluciono :crying_cat_face: 

![image](https://user-images.githubusercontent.com/42187168/64575545-d2409800-d34a-11e9-9446-5ebc3d33346b.png)

![image](https://user-images.githubusercontent.com/42187168/64575555-e2f10e00-d34a-11e9-9e0a-dd5eb57506bc.png)

**Comment by gpvidal** [comment]
Hola @isavega ,

Probaste realizar el mismo procedimiento con esta guía?
https://medium.com/coding-blocks/creating-user-database-and-adding-access-on-postgresql-8bfcd2f4a91e

Nos cuentas!

Saludos,

**Comment by isavega** [comment]
Me sigue apareciendo mi usuario como postgres, me permite crear la base de datos pero no tener mis propias credenciales. Como no tengo credenciales, no puedo configurar mi archivo .envrc. 

![image](https://user-images.githubusercontent.com/42187168/64636266-bc2ce900-d3d7-11e9-9f7d-33c5ed9ca10b.png)

**Comment by gpvidal** [comment]
Ahhhh! Pero ojo que lo que te entrega el commando `\conninfo` es para la conexión actual a `psql` y, dado que lo haces con el comando `sudo -u postgres psql` siempre te responderá eso.

Dado que ya hiciste el proceso arriba, sólo te faltaría configurar las variables de entorno: `DB_USERNAME` con valor `isavega`, `DB_PASSWORD` con valor `isa123` y `DB_NAME` con valor `mydb` y todo debería funcionar. Puedes ver en la Wiki, la sección de Tips.

Ahora, una prueba rápida que puedes hacer es ir al archivo `src/config/database.js` y reemplazar `DB_USERNAME`, `DB_PASSWORD` y `DB_NAME` con los valores que hay más arriba. Con esto también debería funcionar (para probar), pero las variables de entorno es la configuración recomendada.

Ya que hiciste tu configuración pública aquí, quizás te convendría cambiar algunos datos en tu configuración :stuck_out_tongue: 

Saludos!

**Comment by isavega** [comment]
Al final el problema no era ese! Postgres no me deja usar un usuario distinto al de la maquina virtual, en este caso "isabel". Me dejaba crear un usuario "isavega" pero las credenciales no me lo reconocian. Ahora que cambié al original no tuve problemas, muchisimas gracias :smile:

**Comment by gpvidal** [comment]
Súper!
